# Generated by Django 4.1.3 on 2022-12-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product_description_en_product_description_tr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paind',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('vaiting', 'VAITING'), ('confirmed', 'CONFIRMED'), ('paid', 'PAID'), ('delivered', 'DELIVERED')], default='VAITING', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stop_list',
            field=models.BooleanField(default=False),
        ),
    ]
