# Generated by Django 4.1.3 on 2022-12-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_paind_order_paid_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='name_ru',
        ),
    ]
