# Generated by Django 4.1.3 on 2022-12-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_name_en_category_name_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_en',
            new_name='name_ru',
        ),
    ]
