# Generated by Django 4.1.3 on 2022-12-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_description_en_product_description_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
