# Generated by Django 4.1.3 on 2022-12-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_user_new_phone_user_otp_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dish',
            field=models.BooleanField(default=True),
        ),
    ]
