# Generated by Django 4.1.3 on 2022-12-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_product_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dish',
        ),
    ]
