# Generated by Django 4.1.3 on 2022-12-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_product_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dish',
            field=models.CharField(choices=[('0', '0'), ('3000', '3000'), ('4000', '4000'), ('6000', '6000'), ('10000', '10000')], default='0', max_length=100),
        ),
    ]
