# Generated by Django 3.1.14 on 2023-02-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20230207_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.order'),
        ),
    ]
