# Generated by Django 3.1.14 on 2023-02-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_location_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.CharField(max_length=400, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.CharField(max_length=400, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=400, null=True, verbose_name='Name'),
        ),
    ]
